# Generated by Django 4.2.6 on 2023-11-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_remove_tutorial_text_tutorial_body_tutorial_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
