# Generated by Django 4.2.6 on 2023-11-30 17:34

from django.db import migrations
import utils.constraint_fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogimage',
            old_name='tutorial',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=utils.constraint_fields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='blog-media/'),
        ),
    ]
