# Generated by Django 4.2.6 on 2023-11-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('term_type', models.PositiveSmallIntegerField(choices=[(0, 'privacy'), (1, 't&c')], default=0)),
            ],
            options={
                'verbose_name': 'term',
                'verbose_name_plural': 'terms',
            },
        ),
    ]
