# Generated by Django 4.2.6 on 2023-11-16 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_name', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=10)),
                ('about', models.TextField(max_length=500)),
                ('project_logo', models.URLField(blank=True, null=True)),
                ('source', models.URLField()),
                ('source_code', models.URLField(blank=True, null=True)),
                ('doc_type', models.PositiveSmallIntegerField(choices=[(0, 'pgm-lang'), (1, 'tool')], default=0)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(0, 'Open collective'), (1, 'Github'), (2, 'Buy me a coffee'), (3, 'Patreon')], default=1)),
                ('username', models.CharField(max_length=45, validators=[utils.validators.name_validator])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsapp.project')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(0, 'Reddit'), (1, 'Twitter'), (2, 'Discord'), (3, 'Mastodon'), (4, 'Stackoverflow')], default=4)),
                ('username', models.CharField(max_length=45, validators=[utils.validators.name_validator])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docsapp.project')),
            ],
        ),
    ]
