# Generated by Django 4.2.6 on 2023-11-20 05:57

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_name',
            field=models.CharField(max_length=40, validators=[utils.validators.name_validator]),
        ),
    ]
