# Generated by Django 4.2.6 on 2023-11-20 05:57

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0002_additionallink_alter_project_unique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unique_name',
            field=models.CharField(max_length=40, unique=True, validators=[utils.validators.name_validator]),
        ),
    ]
