# Generated by Django 4.2.6 on 2023-11-20 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0003_alter_project_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionallink',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='docsapp.project'),
            preserve_default=False,
        ),
    ]
