# Generated by Django 4.2.6 on 2023-11-21 04:37

from django.db import migrations, models
import docsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0004_additionallink_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='unique_id',
            field=models.CharField(default=docsapp.models.generate_id, max_length=20, null=True),
        ),
    ]
