# Generated by Django 4.2.6 on 2023-11-21 04:38

from django.db import migrations, models
import docsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0005_project_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='unique_id',
            field=models.CharField(default=docsapp.models.generate_id, max_length=20, unique=True),
        ),
    ]
