# Generated by Django 4.2.6 on 2023-11-23 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0007_documentation_docpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='docpage',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
