# Generated by Django 4.2.6 on 2023-11-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0008_docpage_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='doc_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
