# Generated by Django 4.2.6 on 2023-11-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0009_project_doc_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='sidebar',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
