# Generated by Django 4.2.6 on 2023-11-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsapp', '0010_documentation_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Open collective'), (1, 'Github'), (2, 'Buy me a coffee'), (3, 'Patreon'), (4, 'Paypal')], default=1),
        ),
    ]
